### ISSUE TITLE
Auro input date field should accept MM/YYYY format

### ISSUE THREAD

**Issue by DZwell** [AlaskaAirlines/auro-input#115]
## Is your feature request related to a problem? Please describe.

Having the auro input accept MM/YYYY format would prevent us from needing to manually add the century (e.g `"20${twoDigitYear}"`

## Describe the solution you'd like
Adding a case like this to `base-input.js`: `        case 'month-fullYear':
          config = {
            date: true,
            datePattern: [
              'm',
              'Y'
            ]
          };`

Happy to submit a PR.

**Comment by blackfalcon** [comment]
@DZwell  this seems like the right thing to support. In order to keep from creating a breaking change, yes, `month-fullYear` is the appropriate API option. 

There is additional work being done to auro-input so please branch from and submit a PR to the `v2.3-rc` branch. 

Also, please update the Date Format section of the demo document.
