### ISSUE TITLE
Allow overriding default error text

### ISSUE THREAD

**Issue by v-aanwuri** [AlaskaAirlines/auro-input#134]
## Is your feature request related to a problem? Please describe.

We want to be able to change the error text that says "Please fill out this field." while still having the Auto component handle validation.

## Describe the solution you'd like

We'd like to set a property that can change the error text without forcing the error to be displayed.
For example, the following code: 
```
<auro-input id="demo1" defaultError="My custom error text here!"></auro-input>
```
would result in the input box displaying the text "My custom error text here!" when the input is empty but otherwise would not display.

## Describe alternatives you've considered

This is not an immediate blocker. Alternatives include doing custom error validation or just ignoring it.

## Additional context

This request stemmed from the desire to improve the accessibility of our text boxes by displaying an error that includes the name of the field, which will help a screen reader identify which field has the error.

**Comment by blackfalcon** [comment]
After a review of the request and the code, internally we already support a feature for inserting a custom validity statement. So the scope of this issue is really to address a bug that we should have exposed this prop to the public API. 

This feature closely resembles the native HTMLObjectElement.setCustomValidity feature, so it will be documented as such.
