### ISSUE TITLE
New (or optional) treatment for optional fields

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-input#171]
## Is your feature request related to a problem? Please describe.

In building out the planbook widget using auro components, I noticed that the optional input and combobox fields draw more attention to them and take up more label space than desired by requiring them to say "(optional)". I'm hoping to save horizontal space AND only give optional fields the attention they warrant.

![image](https://user-images.githubusercontent.com/34354487/185002536-57224da8-8f2e-471b-8d60-815b496a5f36.png)

## Describe the solution you'd like

I think we would have a different pattern other than text for identifying required vs optional fields - where the required field draws more attention than the optional, but not where it is indicated by text alone. 
Ideally, could we make displaying "(optional)" or a required field an option within the component? In the widgets the fields are primarily optional and it is different from filling out a more task heavy join form where it might be more necessary to indicate what is/is not required.

## Describe alternatives you've considered

Another alternative is to indicate required fields with an * by the label, this is a common pattern, and not to indicate anything on optional fields, but I am open to other pattern options.

**Comment by blackfalcon** [comment]
While I agree that there is an opportunity to discuss optional vs required, I can't agree that this conversation should be based on saving horizontal space. I say this because `discount code` is not a constant. E.g. localized to Spanish, this string is changed to `código de descuento`. 

The prevailing argument is that typically most of the fields are required, so to reduce cognitive load, designating the optional field is preferred. But... what about the cases where most of the fields are optional? You have an adverse effect. 

The following links gives weight to many parts of these arguments. 

https://uxdesign.cc/form-field-required-vs-optional-9b4d7cdbf400
https://www.nngroup.com/articles/required-fields/

IMHO, Auro shouldn't really dictate an opinion on this. TBH, the only reason we need to designate optional vs required is purely functional and for accessibility reasons. Whether or not we illustrate `optional` or `required` is really up to the end user of the input element. 

I propose that there could be an option to show a label either way. E.g. if all the form elements are required, then only illustrate the `optional` label. Vice versa, if all the fields are optional, only illustrate which ones may be `required`. I still advocate for this type of illustration to make this information easy for users to consume and not rely on error messages to inform the user of incomplete information. 

Also, this update would stretch beyond auro-input and have to be updated in all form elements. 

Having said all of this, I am also of the opinion that the asterisk is not a good direction and I agree with the [arguments in this article](https://uxdesign.cc/form-field-required-vs-optional-9b4d7cdbf400).

**Comment by blackfalcon** [comment]
@blackfalcon to schedule meeting with @leeejune about how to move forward.

**Comment by blackfalcon** [comment]
The details around resolving this issue from design are slow-moving at best. IA m recommending that we move this issue to the BACKLOG and when there is a design resolution we will consider how to move forward then.

**Comment by blackfalcon** [comment]
Since updating this issue, there is no priority from design to make this change. Labeling as abandoned and unless told otherwise in the next 30 days, this issue will be close.
