### ISSUE TITLE
Auro input and Auro select don't have matching heights

### ISSUE THREAD

**Issue by DZwell** [AlaskaAirlines/auro-input#184]
Auro input and select have a mismatch in height. It's noticeable when they're next to each other in a form. The bug was initially addressed on the select side in [this issue](https://github.com/AlaskaAirlines/auro-select/issues/81). Per a conversation with Jordan Jones, I'm filing the same bug this time on the input side.

Unrelated, but if you look closely you can see a white background protruding from behind the select field.

## Expected behavior

All form fields should share a consistent height.

## Screenshots

![image](https://user-images.githubusercontent.com/10947475/191125568-64b264a8-5581-49bf-ae25-91a34e062576.png)
![image](https://user-images.githubusercontent.com/10947475/191125591-a87cf7e6-dd1b-4ec1-af23-3659040ff506.png)
![image](https://user-images.githubusercontent.com/10947475/191125622-4a64a4c3-3668-4c4d-be32-ef13bcf7dafa.png)

## Desktop (please complete the following information):

 - Browser [Firefox]

**Comment by blackfalcon** [comment]
Issue is being reviewed and prioritized to address.

**Comment by braven112** [comment]
@DZwell Can you let us know what versions of auro-input and auro-select you are using?  Also can you let us know what the font size of the body is?

We created this demo page that uses the latest versions of auro-input and auro-select and can't repro this issue there.

https://auro-examples.vercel.app/forms

There is a known discrepancy in auro-combobox that we plan to address in the upcoming sprint so that all 3 of these input types (plus datepicker) are all the same size.

**Comment by DZwell** [comment]
@braven112 
auro-input: 2.9.0
auro-select: 2.5.1
font-size: 16px

I looked at the forms demo and the height of the input and height of the select are different there.
 Input: 61px
Select: 58px

The difference is small but still noticeable.

![image](https://user-images.githubusercontent.com/10947475/191618930-20e3eaab-fdf5-4177-bb07-389f83af93f4.png)


I did a quick test just to see how the stock HTML input/select elements behave and they both have consistent heights of 22px.

Thanks for all the help with this, I appreciate it.
