### ISSUE TITLE
pattern property having adverse effects on non-required inputs

### ISSUE THREAD

**Issue by ashleybiermannalaska** [AlaskaAirlines/auro-input#200]
## Some regex patterns used in the pattern property trigger the red helper text and red required triangle to show after navigating away from a non-required input. 

**Note**: The red outline on the input does *not* show up

## Expected behavior
When a user navigates into a non-required field, then leaves it empty and navigates away, we expect to see no red triangle and no red helper text.

## To Reproduce
Code below indicates component usage with expected and unexpected behavior. Intentionally left the non-relevant fields as '`...`'
```
<auro-input id=...
label="....
autoComplete=....
required={false}  <--- ((A))
name=....
onChange=....
// pattern="^([a-zA-Z0-9]{1,25})?$" <--- ((B))
pattern="^[ A-Za-záéÉíóúüÜñÑ][A-Za-záéÉíóúüÜñÑ' -]{0,30}$" <--- ((C))
message="Please enter a valid traveler number (less than 25 characters)."
value=....
 ></auro-input>
```
### Behaviors
- ((A)) We experimented with removing `required` property completely. when removed (with the troublesome regex still included), the behavior was as expected. When trying `required={false}`, the unexpected behavior remained
- ((B)) this pattern is an example that yields *expected* behavior
- ((C)) this pattern is an example that yields *unexpected* behavior

## Steps to reproduce the behavior:

1. In an auro-input, use the regex pattern in ((C)), shown above, at the same time as `required`
2. Click inside the input, then away
3. Some parts of an error or helper text are indicated

## Screenshots

This is the expected behavior. It occurs with all versions less than 2.9.0
![Screen Shot 2022-10-11 at 4 46 59 PM](https://user-images.githubusercontent.com/113386737/195218483-673e5819-3f38-4394-92fe-b416e7689ff4.png)

This is the unexpected behavior. It occurs with all versions higher than and including 2.9.0
![Screen Shot 2022-10-11 at 4 47 19 PM](https://user-images.githubusercontent.com/113386737/195218488-d4a3dc0c-7eee-4b1a-af2e-f113a34d821f.png)

## Desktop (please complete the following information):
 - OS: Mac
 - Browser: Chrome

## Additional context
We're working on the E-Commerce booking team :) Please reach out if you need

**Comment by jordanjones243** [comment]
@ashleybiermannalaska The issue here seems to be the regex pattern. The regex pattern on point C (`^[ A-Za-záéÉíóúüÜñÑ][A-Za-záéÉíóúüÜñÑ' -]{0,30}$`) does not allow for an empty string. Our code tests the value of `auro-input` against the regex pattern and it sets the validity attribute to `badInput` if it fails, which is why you are seeing the unexpected behavior on non-required inputs. Although, the border should be outlined in red.

Additionally, the required attribute is a boolean attribute, so you cannot set it to false within the HTML element. Removing it from the element gives it a value of false, while its presence gives it a value of true. Having `required={false}` will still make the input field required.

As a team we will discuss whether or not patterns should be validated on empty strings, but your bug could be fixed if your regex pattern allows for the string to be empty.

**Comment by ashleybiermannalaska** [comment]
> 

this occurred with 2.9.0 and higher

**Comment by blackfalcon** [comment]
@jordanjones243 thanks for that detailed feedback. 

@ashleybiermannalaska it's a common misunderstanding around HTML boolean values. In fact, so much so that I include this in a deck I give at presentations and I am amazed at how many surprised faces I see in the audience. 

Here is a brief article that helps explain this in the context of HTML attributes and ARIA attributes that are tri-state. 

https://hidde.blog/boolean-attributes-in-html-and-aria-whats-the-difference/#:~:text=The%20attribute%2C%20when%20present%2C%20can%20have%20any%20value

**Comment by blackfalcon** [comment]
After discussion, it has been determined that the element is working as expected when it comes to `pattern` behavior. That being said, the issue still persists that when a non-required field is presented with an incorrect regex pattern match, the error state is not consistent. 

### Spec

Address the bug related to the correct presentation of error state

### Exit criteria 

For this issue to be closed, it is expected that the UI will present a full error state without a `required` attribute even with a regex pattern mis-match.

**Comment by jordanchang** [comment]
We are also using auro-input's type="email" attribute on our page and was looking for a solution to skip email validation when the input has no value set. 

Should we remove _type=email_ and migrate over to a _custom email regex_ pattern?
