### ISSUE TITLE
Reverse route value

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-input#230]
## Is your feature request related to a problem? Please describe.
For Flight Search team's planbook initiative, we want to create a reverse route button that would be an icon-only button (UI and Figma not finalized yet - will be worked on by Kayla and coordinated with @leeejune ).

In discussion, it was mentioned that the reverse route button would be a good candidate for auro as this functionality could be used in a lot of pages like homepage, deals, employee travel, as well as planbook.

## Describe the solution you'd like
For our use case, it will be a button similar to on google flights that reverses the inputs of 2 comboboxes.
![image](https://user-images.githubusercontent.com/34354487/217098859-241b78e2-96f6-4e38-b45d-348272848fb0.png)

Not sure if the approach would be specifically a button for reverse route, or just a variant of button that allows for an icon only.

**Comment by lindseyo1123** [comment]
updating to add clarification:

no icons on destination / to like google has
the button does not need animation like google has

**Comment by blackfalcon** [comment]
@jason-capsule42 is working through a POC of how this can work with existing Auro tools and creating a demo to illustrate. @leeejune will work with for a UI to deliver.

**Comment by jason-capsule42** [comment]
Draft PR added and ticket marked as blocked pending resolution of the UI design from @leeejune.

**Comment by leeejune** [comment]
### Context
When starting this work, the idea to use an icon only button for the reverse button came up. As the designer, I picked up the idea because there were requests from other teams wanting an icon only button.

### Current situation with design
I am working on the icon only button and will be getting feedback on it next week. The reverse icon button will be using this new icon only button.

### Options for next steps

- Publish an example without design and update it once the button design is complete (meanwhile the team who needs this will design a temporary button for their goals)
- Wait for button design to be complete and publish example

We will also need to discuss how where we will add these specific use cases if we continue to add them on the doc site in the future.

**Comment by jason-capsule42** [comment]
Given team discussion on what we should do as an initial release the PR is presented for review with a functional version that does not incorporate the icon only button design work described earlier in this ticket.

Initial release will include a functional only version with limited custom CSS to layout the default auro-input and auro-button elements.

**Comment by blackfalcon** [comment]
For reference. The completed demo can be found here. https://auro.alaskaair.com/components/auro/input
