### ISSUE TITLE
Error border on disabled input

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-input#288]
### Please verify the version of auro-input you have installed

2.17

### Please describe the bug

Go to https://www.alaskaair.com/search/
Select "Use miles"
See error
https://github.com/AlaskaAirlines/auro-input/assets/5118118/f81a3b9c-5dd4-4b3d-aacf-d55e72be85d6

### Reproducing the error on the docsite

None

### Expected behavior

No red border showing when selecting use miles

### Additional context

Contact Reji on the flight search team for more info.  Might be related to #274

**Comment by Patrick-Daly-AA** [comment]
After initial analysis, it looks like this may be because of a token error.  @blackfalcon is investigating.

**Comment by blackfalcon** [comment]
This issue was resolved with this PR back in Jan 6th. 

- https://github.com/AlaskaAirlines/auro-input/pull/276/files#diff-c0a5ddd5b365322730802e8cb15c95c3b6e965cbd3e569c69a2f089753844cdb

The issue persists due to outdated dependencies. 

`"@aurodesignsystem/auro-combobox": "^1.8.1", => "@aurodesignsystem/auro-combobox": "^1.9.5",`

auro-combobox has an internal dependency on auro-input `v2.15.1`. Interestingly, that is the only version that has auro-input's disabled/error UI bug. This was fixed with the linked PR and fixed with auro-input `v2.15.2`.

It should be pointed out that the UI with the issue also has auro-input `v2.16.1` installed, but due to the fact that auro-combobox loads BEFORE auro-input, its dependency version is loaded first, and the later version is ignored. 

#### Actions items that need to be addressed per this issue

1. When this issue was created it states that `v2.17` is installed and that is incorrect. We need to make sure that we have the right data. 
2. I am unsure if the team was asked to update their dependencies or not as that would have resolved the issue. The project is far behind in multiple packages. 
3. The Auro team needs to be 100% accurate in releasing updates ensuring that the listed dependencies, dev and peer, are all up to date. 
4. Elements that have other Auro element dependencies need to be clearly identified 
5. Implementing a system of [npm overrides](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides) should be communicated via the Auro doc site.

@lindseyo1123 @Patrick-Daly-AA @braven112 please communicate back to the team that there is no code fix to address this as the issue has already been resolved with the original issue submitted by @dkt2.
