### ISSUE TITLE
Inconsistent UI response to X action with element at variable widths

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-input#329]
### Please verify the version of auro-input you have installed

@latest

### Please describe the bug

While investigating #327 I discovered the following UI bug. 

Please see this CodePen: https://codepen.io/blackfalcon/pen/MWMVjVo

To repro the issue, please do the following in the provided example:

- Tab in, then tab out of the element and notice that the warning icon appears.
- Tab into the element and enter a value, notice the warning AND the "x" button appears.
- DO NOT LEAVE the element while in this state.
- With BOTH the warning and the "x" within the element, click on the "x"
- Notice this does not clear the value, but only removes the warning.

### Reproducing the error on the docsite

This issue is reproducible on the Auro docsite

### Expected behavior

It is expected that when using the `auro-input` element at any width, the `x` button action should clear the value of the input. 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Additional context

This and issue #327 may be related.

**Comment by Patrick-Daly-AA** [comment]
Closing this as an implementation error.  The behavior seen where trying to click the X on an input where the input field can resize is because before the click event can even fire, validation is run, and the error is cleared.

Our recommendation is that input should not be implemented to have error validation and resizing and allow for clearing with the x button.  Best practice recommendation is that the input field should be a set width, and in most known uses of Auro-input we see a fixed width used.
