### ISSUE TITLE
auro-input: cursor jumps to front when password toggle clicked

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-input#33]
## To Reproduce
1. Go to http://auro.alaskaair.com/components/auro/input
2. Scroll down to the password input
3. Type in some characters
4. Click on the show password icon
5. Note that the cursor jumps to the front of the input

## Expected behavior
The cursor should remain in the position it was when clicking the icon

**Comment by blackfalcon** [comment]
This was actually implemented as a feature if I remember correctly. The desire from UX was that when a user leaves and then comes back to the input, the cursor is always at the front. 

@geoffrich you remember this?

**Comment by geoffrich** [comment]
@blackfalcon I'm not quite sure what you mean by a user leaving and returning to the input. I don't remember implementing any logic like that, but that doesn't mean we didn't. This is specifically about the password toggle, though, which wasn't part of the original design.

Here's a gif of what Jason is reporting in Chrome. Is it intentional that clicking "show password" moves the cursor to the beginning? 
![password](https://user-images.githubusercontent.com/4992896/119524139-3af3c200-bd32-11eb-9a20-8ca767e5eea7.gif)

**Comment by jason-capsule42** [comment]
> @blackfalcon I'm not quite sure what you mean by a user leaving and returning to the input.

When you click on the show password icon the default browser behavior is that focus is technically removed from the input since you are interacting with a different element in the DOM. Then we are putting focus back in the input. I believe we just need to make sure that when we return focus to where it was when we left (if possible) or just return to the end of the string.

**Comment by blackfalcon** [comment]
My timing may be off, but this has been there for a long time. 

https://github.com/AlaskaAirlines/auro-input/commit/2c907d57cbef71f78c3bc5d6f1b7dd416d79871c#diff-aedef65e662f6f161de4dda6e34b704053e1778b73199c5d58273e4d66c7f4fbR160

I am assuming that this is the call that is doing this. 

I know that there was a decision made when we first built this that when a user blurs and returns, the cursor was to be at the beginning, specifically for cases where there was a smaller input and a long string inside of it. 

IMHO, I don't see this as a bug.
